name: auth_app
description: "A new Flutter project with Supabase authentication."

# Define la versión y el entorno para la aplicación Flutter
environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencias que tu aplicación necesita
dependencies:
  flutter:
    sdk: flutter
  
  # Supabase para la autenticación y la base de datos
  supabase_flutter: ^2.8.4
  
  # Para gestionar imágenes
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  
  # Iconos y widgets de Material Design
  cupertino_icons: ^1.0.6

# Dependencias solo para desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Configuración de Flutter
flutter:
  uses-material-design: true
  
  # Agregar assets (imágenes, iconos, etc.)
  # assets:
  #   - assets/images/